-- Generated by Oracle SQL Developer Data Modeler 4.0.3.853
--   at:        2015-06-14 22:34:54 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g


drop sequence "KAT0013"."LEAGUE_IDL_SEQ";
drop sequence "KAT0013"."MATCH_IDM_SEQ";
drop sequence "KAT0013"."PLAYER_IDP_SEQ";
drop sequence "KAT0013"."REFEREE_IDR_SEQ";
drop sequence "KAT0013"."STADIUM_IDS_SEQ";
drop sequence "KAT0013"."TEAM_IDT_SEQ";


DROP TABLE Capacity_hist CASCADE CONSTRAINTS ;

DROP TABLE Controls CASCADE CONSTRAINTS ;

DROP TABLE Forward CASCADE CONSTRAINTS ;

DROP TABLE League CASCADE CONSTRAINTS ;

DROP TABLE MATCH CASCADE CONSTRAINTS ;

DROP TABLE Player CASCADE CONSTRAINTS ;

DROP TABLE Plays CASCADE CONSTRAINTS ;

DROP TABLE Referee CASCADE CONSTRAINTS ;

DROP TABLE Stadium CASCADE CONSTRAINTS ;

DROP TABLE Statistics CASCADE CONSTRAINTS ;

DROP TABLE Team CASCADE CONSTRAINTS ;

CREATE TABLE Capacity_hist
  (
    ids        INTEGER NOT NULL ,
    start_date DATE NOT NULL ,
    end_date   DATE NOT NULL ,
    capacity   INTEGER NOT NULL
  ) ;
ALTER TABLE Capacity_hist ADD CONSTRAINT Capacity_hist_PK PRIMARY KEY ( start_date, ids, end_date ) ;

CREATE TABLE Controls
  ( idm INTEGER NOT NULL , idr INTEGER NOT NULL
  ) ;
ALTER TABLE Controls ADD CONSTRAINT Controls_PK PRIMARY KEY ( idm, idr ) ;

CREATE TABLE Forward
  (
    idp        INTEGER NOT NULL ,
    max_speed  INTEGER NOT NULL ,
    first_name VARCHAR2 (64) NOT NULL ,
    last_name  VARCHAR2 (64) NOT NULL ,
    birthdate  DATE NOT NULL ,
    weight     INTEGER NOT NULL ,
    height     INTEGER NOT NULL ,
    position   CHAR NOT NULL ,
    idt        INTEGER NOT NULL
  ) ;
ALTER TABLE Forward ADD CONSTRAINT Forward_PK PRIMARY KEY ( idp ) ;

CREATE TABLE League
  (
    idl    INTEGER NOT NULL ,
    name   VARCHAR2 (32) NOT NULL ,
    rounds INTEGER NOT NULL
  ) ;
ALTER TABLE League ADD CONSTRAINT League_PK PRIMARY KEY ( idl ) ;

CREATE TABLE MATCH
  (
    idm    INTEGER NOT NULL ,
           DATETIME DATE NOT NULL ,
    ROUND  INTEGER NOT NULL ,
    result VARCHAR2 (5) ,
    video_report BLOB ,
    idl      INTEGER NOT NULL ,
    idt_home INTEGER NOT NULL ,
    idt_away INTEGER NOT NULL ,
    ids      INTEGER NOT NULL
  ) ;
ALTER TABLE MATCH ADD CONSTRAINT Match_PK PRIMARY KEY ( idm ) ;

CREATE TABLE Player
  (
    idp        INTEGER NOT NULL ,
    first_name VARCHAR2 (64) NOT NULL ,
    last_name  VARCHAR2 (64) NOT NULL ,
    birthdate  DATE NOT NULL ,
    weight     INTEGER NOT NULL ,
    height     INTEGER NOT NULL ,
    position   CHAR NOT NULL ,
    idt        INTEGER NOT NULL
  ) ;
ALTER TABLE Player ADD CONSTRAINT Player_PK PRIMARY KEY ( idp ) ;

CREATE TABLE Plays
  (
    idp          INTEGER NOT NULL ,
    idm          INTEGER NOT NULL ,
    goals        INTEGER NOT NULL ,
    assists      INTEGER NOT NULL ,
    yellow_cards INTEGER NOT NULL ,
    red_card     INTEGER NOT NULL ,
    minutes      INTEGER NOT NULL
  ) ;
ALTER TABLE Plays ADD CONSTRAINT Plays_PK PRIMARY KEY ( idp, idm ) ;

CREATE TABLE Referee
  (
    idr        INTEGER NOT NULL ,
    first_name VARCHAR2 (64) NOT NULL ,
    last_name  VARCHAR2 (64) NOT NULL ,
    birthdate  DATE NOT NULL ,
    license    CHAR (1) NOT NULL
  ) ;
ALTER TABLE Referee ADD CONSTRAINT Referee_PK PRIMARY KEY ( idr ) ;

CREATE TABLE Stadium
  (
    ids      INTEGER NOT NULL ,
    name     VARCHAR2 (64) NOT NULL ,
    capacity INTEGER NOT NULL ,
    built    DATE NOT NULL
  ) ;
ALTER TABLE Stadium ADD CONSTRAINT Stadium_PK PRIMARY KEY ( ids ) ;

CREATE TABLE Statistics
  (
    idm          INTEGER NOT NULL ,
    goals        INTEGER NOT NULL ,
    yellow_cards INTEGER NOT NULL ,
    red_cards    INTEGER NOT NULL
  ) ;
ALTER TABLE Statistics ADD CONSTRAINT Statistics_PK PRIMARY KEY ( idm ) ;

CREATE TABLE Team
  (
    idt        INTEGER NOT NULL ,
    name       VARCHAR2 (64) NOT NULL ,
    foundation DATE NOT NULL ,
    idl        INTEGER NOT NULL
  ) ;
ALTER TABLE Team ADD CONSTRAINT Team_PK PRIMARY KEY ( idt ) ;

ALTER TABLE Capacity_hist ADD CONSTRAINT Capacity_hist_Stadium_FK FOREIGN KEY ( ids ) REFERENCES Stadium ( ids ) ;

ALTER TABLE Controls ADD CONSTRAINT FK_ASS_2 FOREIGN KEY ( idm ) REFERENCES MATCH ( idm ) ;

ALTER TABLE Controls ADD CONSTRAINT FK_ASS_3 FOREIGN KEY ( idr ) REFERENCES Referee ( idr ) ;

ALTER TABLE Forward ADD CONSTRAINT Forward_Player_FK FOREIGN KEY ( idp ) REFERENCES Player ( idp ) ;

ALTER TABLE MATCH ADD CONSTRAINT Match_Away_Team_FK FOREIGN KEY ( idt_away ) REFERENCES Team ( idt ) ;

ALTER TABLE MATCH ADD CONSTRAINT Match_Home_Team_FK FOREIGN KEY ( idt_home ) REFERENCES Team ( idt ) ;

ALTER TABLE MATCH ADD CONSTRAINT Match_League_FK FOREIGN KEY ( idl ) REFERENCES League ( idl ) ;

ALTER TABLE MATCH ADD CONSTRAINT Match_Stadium_FK FOREIGN KEY ( ids ) REFERENCES Stadium ( ids ) ;

ALTER TABLE Player ADD CONSTRAINT Player_Team_FK FOREIGN KEY ( idt ) REFERENCES Team ( idt ) ;

ALTER TABLE Plays ADD CONSTRAINT Plays_Match_FK FOREIGN KEY ( idm ) REFERENCES MATCH ( idm ) ;

ALTER TABLE Plays ADD CONSTRAINT Plays_Player_FK FOREIGN KEY ( idp ) REFERENCES Player ( idp ) ;

ALTER TABLE Statistics ADD CONSTRAINT Statistics_Match_FK FOREIGN KEY ( idm ) REFERENCES MATCH ( idm ) ;

ALTER TABLE Team ADD CONSTRAINT Team_League_FK FOREIGN KEY ( idl ) REFERENCES League ( idl ) ;

CREATE OR REPLACE TRIGGER FKNTM_Statistics BEFORE
  UPDATE OF idm ON Statistics BEGIN raise_application_error(-20225,'Non Transferable FK constraint  on table Statistics is violated');
END;
/

CREATE SEQUENCE League_idl_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER League_idl_TRG BEFORE
  INSERT ON League FOR EACH ROW WHEN (NEW.idl IS NULL) BEGIN :NEW.idl := League_idl_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE Match_idm_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER Match_idm_TRG BEFORE
  INSERT ON MATCH FOR EACH ROW WHEN (NEW.idm IS NULL) BEGIN :NEW.idm := Match_idm_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE Player_idp_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER Player_idp_TRG BEFORE
  INSERT ON Player FOR EACH ROW WHEN (NEW.idp IS NULL) BEGIN :NEW.idp := Player_idp_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE Referee_idr_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER Referee_idr_TRG BEFORE
  INSERT ON Referee FOR EACH ROW WHEN (NEW.idr IS NULL) BEGIN :NEW.idr := Referee_idr_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE Stadium_ids_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER Stadium_ids_TRG BEFORE
  INSERT ON Stadium FOR EACH ROW WHEN (NEW.ids IS NULL) BEGIN :NEW.ids := Stadium_ids_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE Team_idt_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER Team_idt_TRG BEFORE
  INSERT ON Team FOR EACH ROW WHEN (NEW.idt IS NULL) BEGIN :NEW.idt := Team_idt_SEQ.NEXTVAL;
END;
/


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            11
-- CREATE INDEX                             0
-- ALTER TABLE                             24
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           7
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          6
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
