SELECT DISTINCT Concat('Mr/Mrs ' || first_name, ' '||last_name) from Player

SELECT UPPER(first_name),LOWER(first_name),INITCAP(first_name), birthdate
FROM PLAYER
WHERE LOWER(first_name) in ('maite','kaseem','dakota') OR LOWER(first_name) LIKE 's%' OR birthdate BETWEEN '23.02.95' AND '19.05.95'

SELECT *
FROM MATCH
WHERE RESULT IS NULL
ORDER BY DATETIME desc

SELECT IDS,NAME,CAPACITY,TRUNC(CAPACITY,-2)
FROM STADIUM

SELECT AVG(CAPACITY)
FROM STADIUM
SELECT INSTR('CORPORATE FLOOR','OR', 3, 2)
  "Instring" FROM DUAL;


SELECT FIRST_NAME FROM PLAYER

SELECT FIRST_NAME,SUBSTR(FIRST_NAME,1,3), LENGTH(FIRST_NAME), INSTR(FIRST_NAME,'e'), LPAD(FIRST_NAME,15,'*'), RPAD(FIRST_NAME,15,'*')
, TRIM(LEADING 'M' FROM FIRST_NAME), REPLACE(FIRST_NAME,'D', '--D')
FROM PLAYER

SELECT AVG(CAPACITY),ROUND(AVG(CAPACITY)), TRUNC(AVG(CAPACITY),2),TRUNC(AVG(CAPACITY),-3), FLOOR(MOD(AVG(CAPACITY),2)), CEIL(MOD(AVG(CAPACITY),2))
FROM STADIUM

SELECT BIRTHDATE,TO_NUMBER(MONTHS_BETWEEN(ADD_MONTHS(BIRTHDATE,3),BIRTHDATE)), TO_CHAR(ADD_MONTHS(BIRTHDATE,1)), NEXT_DAY(BIRTHDATE, 1), LAST_DAY(BIRTHDATE), ROUND(BIRTHDATE), TRUNC(BIRTHDATE,'YEAR')
FROM PLAYER

     
SELECT COUNT(NULLIF(EXTRACT(month FROM BIRTHDATE),EXTRACT(month FROM SYSDATE)))
FROM Player;

SELECT IDM,NVL2(RESULT, 'Match was Played', 'Match will be Played')
FROM MATCH;

SELECT IDP, DECODE(position, 'M', 'Midfielder',
  'F', 'Forward',
  'D', 'Defender',
  'Goalkeeper') result 
FROM player;

SELECT T.NAME, P.FIRST_NAME, P.LAST_NAME
FROM TEAM T NATURAL JOIN PLAYER P

SELECT T.NAME, P.FIRST_NAME, P.LAST_NAME
FROM TEAM T JOIN PLAYER P USING (idt)

SELECT T.NAME, P.FIRST_NAME, P.LAST_NAME
FROM TEAM T LEFT OUTER JOIN PLAYER P ON (T.IDT = P.IDT)


SELECT S.IDS, S.NAME, M.DATETIME, M.RESULT
FROM STADIUM S LEFT OUTER JOIN MATCH M ON(S.IDS = M.IDS)

SELECT C.IDM, R.IDR, R.FIRST_NAME || R.LAST_NAME
FROM Controls C FULL OUTER JOIN REFEREE R ON(C.IDR = R.IDR)

SELECT POSITION, COUNT(IDP), ROUND(AVG(WEIGHT),0)
FROM PLAYER
GROUP BY POSITION
HAVING AVG(WEIGHT) >  72


SELECT T.IDT, T.NAME, T.FOUNDATION, COUNT(P.IDP)
FROM TEAM T LEFT OUTER JOIN PLAYER P ON (T.IDT = P.IDT)
GROUP BY GROUPING SETS(
  (T.IDT,T.NAME),
  (T.FOUNDATION,T.NAME)
)

SELECT IDP,FIRST_NAME, LAST_NAME, POSITION
FROM PLAYER
UNION ALL
SELECT IDP,FIRST_NAME, LAST_NAME, POSITION
FROM FORWARD
WHERE MAX_SPEED > 35
ORDER BY LAST_NAME


SELECT *
FROM STADIUM S
WHERE NOT EXISTS (
                  SELECT *
                  FROM CAPACITY_HIST CH
                  WHERE S.IDS = CH.IDS
                  )

SELECT COUNT(*)
FROM PLAYER
WHERE (IDT,POSITION) IN(
                        SELECT IDT,POSITION
                        FROM PLAYER
                        WHERE IDT IN (1,2,3,4)
                        AND POSITION = ANY ('D','F','G')
                        AND HEIGHT > ALL (170,180)
                        )
WITH 
STADIUMS_LIST AS(
  SELECT S.*, (SELECT COUNT(*) FROM MATCH WHERE IDS=S.IDS) POCET_ZAPASU
  FROM STADIUM S),
CAPACITY_OF_STADIUMS AS(
  SELECT AVG(CAPACITY)
  FROM STADIUM
)
SELECT *
FROM STADIUMS_LIST
WHERE CAPACITY > (SELECT * FROM CAPACITY_OF_STADIUMS)

SELECT * FROM MATCH
SELECT * FROM STATISTICS
SELECT * FROM REFEREE

INSERT INTO STATISTICS VALUES(2,2,4,1);
INSERT INTO STATISTICS(IDM,GOALS,YELLOW_CARDS,RED_CARDS) VALUES(3,1,1,0);
INSERT INTO REFEREE(FIRST_NAME,LAST_NAME,BIRTHDATE,LICENSE) SELECT FIRST_NAME,LAST_NAME,BIRTHDATE,LICENSE FROM REFEREE WHERE IDR = 1;

UPDATE REFEREE SET FIRST_NAME = 'DAVID' WHERE IDR = 11;
DELETE FROM REFEREE WHERE IDR = 11;

ALTER TABLE PLAYER ADD CONSTRAINT player_position CHECK (position IN ('G','D','M','F'))


CREATE OR REPLACE NOFORCE VIEW view_teams_players
AS
SELECT T.IDT AS "TEAM ID", T.NAME AS "TEAM NAME", P.FIRST_NAME||' '||P.LAST_NAME AS "PLAYER NAME", P.BIRTHDATE
FROM TEAM T
JOIN PLAYER P ON T.IDT = P.IDT
ORDER BY T.IDT
WITH READ ONLY CONSTRAINT view_teams_players_read_only;

SELECT T.IDT, T.NAME, X.NAME
FROM TEAM T JOIN (SELECT IDL, NAME, ROUNDS FROM LEAGUE) X ON(T.IDL = X.IDL)
ORDER BY T.IDT

CREATE SEQUENCE test_seq
MINVALUE 1
MAXVALUE 999
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

SELECT *
FROM player
WHERE REGEXP_LIKE (first_name, '^Ste(v|ph)en$');


UPDATE MATCH SET RESULT='0:0' WHERE IDM=1;
SAVEPOINT one;
INSERT INTO STATISTICS VALUES(1,0,2,0);
INSERT INTO PLAYS VALUES(1,1,1,0,0,0,90);
SAVEPOINT two;
ROLLBACK TO SAVEPOINT one;
COMMIT;

SELECT *
FROM PLAYER, TEAM
WHERE PLAYER.IDT = TEAM.IDT

SELECT S.IDS, S.NAME, M.DATETIME, M.RESULT
FROM STADIUM S,MATCH M
WHERE S.IDS (+) = M.IDS

